name: build-openclash-repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install apk-tools
        run: |
          wget https://downloads.openwrt.org/snapshots/packages/x86_64/base/apk-tools-static_3.0.5-r1_x86_64.apk
          mkdir apk-tools
          tar -xf apk-tools-static*.apk -C apk-tools
          sudo cp apk-tools/usr/bin/apk /usr/local/bin/
          apk --version

      - name: Import signing key
        run: |
          echo "${{ secrets.OPENCLASH_APK_PRIVATE_KEY }}" > private.sec
          chmod 600 private.sec

      - name: Generate APK repository index
        run: |
          apk mkndx \
            --sign private.sec \
            --output repo/packages.adb \
            repo/*.apk

      - name: Cleanup
        run: |
          rm -f private.sec

      - name: Commit repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add repo/packages.adb
          git commit -m "update apk repository" || exit 0
          git push
